@baseUrl = http://127.0.0.1:8000

# @name home
GET {{baseUrl}}

@accessToken = Bearer {{login.response.body.bearer.access}}

@adminToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGM1ZWQxMjM0NWExMjM0NTY3ODkwMTEiLCJ1c2VybmFtZSI6ImFkbWluIiwiaXNBY3RpdmUiOnRydWUsImlzQWRtaW4iOnRydWUsImlzU3RhZmYiOmZhbHNlLCJpYXQiOjE3ODA4ODAyOTUsImV4cCI6MTc4MDk2NjY5NX0.uQ__CCSMDEQxwQzhAYpuba7f5ZlGSuLUJTMHW6us6dY




###
# @name register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "normal",
  "email": "normal@test.com",
  "password": "Normal!1234",
  "firstName": "Normal",
  "lastName": "Normal"
}

###
# @name login
post {{baseUrl}}/auth/login
Content-Type: application/json

#  {
#      "email": "admin@flightapi.com",
#      "password": "Admin*123"
#  }

    {
      "email": "duygu@test.com",
      "password": "Duygu*123"
    }

### 
# @name logout
post {{baseUrl}}/auth/logout
Authorization: {{accessToken}}

### 

# @name refresh
post {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refresh":"{{login.response.body.bearer.refresh}}"
}

###
# @name userList

get {{baseUrl}}/users/
Authorization: {{accessToken}}

###
# @name userRead
get {{baseUrl}}/users/6a1cc54d48a4b414efae5f50

###
# @name userCreate
post {{baseUrl}}/users
Content-Type: application/json

{
    "username": "admin2",
    "password": "1234",
    "email": "admin2@test.com",
    "firstName": "admin",
    "lastName": "admin",
    "isActive": true,
    "isAdmin": true
}


###
# @name userUpdate
put {{baseUrl}}/users/6a1cc54d48a4b414efae5f50
Content-Type: application/json

{
    "isAdmin": false
}

###
# @name userDelete
delete {{baseUrl}}/users/6a1cc54d48a4b414efae5f50

###
# @name flightCreate
POST {{baseUrl}}/flights
Content-Type: application/json
Authorization: {{accessToken}}

{
  "flightNumber": "XQ450",
  "airline": "SunExpress",
  "departureAirport": "Antalya Airport",
  "departureCity": "Antalya",
  "departureCountry": "Turkey",
  "arrivalAirport": "Dusseldorf Airport",
  "arrivalCity": "Dusseldorf",
  "arrivalCountry": "Germany",
  "departureDate": "2026-07-13T06:20:00.000Z",
  "arrivalDate": "2026-07-13T09:30:00.000Z",
  "capacity": 170,
  "price": 110,
  "currency": "EUR",
  "status": "scheduled",
  "isPublished": false
}

###
# @name flightList
get {{baseUrl}}/flights
Authorization: {{accessToken}}
# Authorization: {{adminToken}}


###
# @name flightRead
get {{baseUrl}}/flights/6a2616062d4b2050a58b1d79
Authorization: {{accessToken}}
